openapi: 3.0.3

info:
  title: Authorization HTTP(S)-JSON
  description: |
    This specification outlines how to realize the _Arrowhead Core Authorization_ service on top of
    either of the HTTP or HTTPS protocols with payloads encoded in JSON. This service allows for
    _resource_ ownwers to check _access-rights_ of _consumers_ attempting to perform operations over
    their protected _resources_.
    
    This interface understands _resources_ as the entities needing protection, e.g., services, events, etc. On the other 
    hand, _consumers_ represents the entities trying to access or consume the previously defined _resources_. Finally, _access-rights_ 
    represents the actions that _subjects_ attempt to performed over the protected _resources_, these can be defined with different levels
    of granularity, such as service consumption, or read or write of data. 

    An authorization rule is defined as an object connecting a _consumer_ with a _resource_, specifying in it the _access-rights_ that the rule
    is managing. An authorization rule can either be a rule granting the specified _access-rights_ or a prohibition, explicitely prohibiting the 
    specified _access-rights_.  

    Moreover, Authorization rules can be defined over a "Group" of _consumers_. This groups can be seen as whitelists or blacklist, in the case of 
    prohibitions. This interface provides methods to manage groups, including the creation, addition or removal of participants. 

    In the context of this document, we understand an _access-right_ to be a string identifier that
    names something a consumer can request that a certain type of service performs on its behalf. We
    also understand an _resource_ to be either a service or an event type available. 
  version: 5.0.0-rc.1

paths:

  /ping:
    get:  
      summary: Endpoint to check the core system availability. 
      description: Returns an OK to indicate that the core system is available. 
      responses:
        '200':
          description: OK

  /policy:
    post:
      summary: A provider can specify one authorization policy, and grant or prohibit a set of access rights to a 
        consumer or group. 
      description: Returns the unique id of the newly created authorization policy. 
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Policy"
      responses:
        '200':
          description: Policy successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  authorization-policy-id:
                    type: string
    get: 
      summary: List Authorization policy
      description: Retrieve a list of all Authorization policy created by the current provider.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Policy'
          headers:
            Limit:
              $ref: '#/components/headers/Limit'

  /policy/{policyId}:
    get:
      summary: Get Authorization policy by ID
      description: Retrieve details of a specific policy by its identifier.
      parameters:
        - name: policyId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
    delete:
      summary: Delete a specific policy
      description: Remove a specified policy by its ID. This revokes the permissions specified in the authorization policy. 
      parameters:
        - name: policyId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Policy deleted successfully
        '404':
          description: Policy not found

  /groups:
    get:
      summary: Get all groups
      description: Retrieve a list of all available groups.
      responses:
        '200':
          description: List of groups retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'

    post:
      summary: Create a new group
      description: Add a new group with an optional initial list of users.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewGroupRequest'
      responses:
        '201':
          description: Group created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
        '400':
          description: Invalid input data

  /groups/{groupId}:
    get:
      summary: Get a specific group
      description: Retrieve information about a specified group.
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Group retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
        '404':
          description: Group not found

    delete:
      summary: Delete a specific group
      description: Remove a specified group by its ID.
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Group deleted successfully
        '404':
          description: Group not found

  /groups/{groupId}/consumers:
    post:
      summary: Add a consumer or group to a group
      description: Add a new or existing consumer or group to the specified group.
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subject'
      responses:
        '200':
          description: User added to the group successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
        '400':
          description: Invalid input data
        '404':
          description: Group not found

  /groups/{groupId}/users/{userId}:
    delete:
      summary: Remove a consumer or from a group
      description: Remove a specified consumer or group from the group.
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Subject removed from group successfully
        '404':
          description: Group or user not found

  /validate:
    post:
      summary: Validate access rights to a resource
      description: |
        Allows for an authorization validation to be sent to the authorization system.

        Queries the authorization system for authorization decision for the specified access right over the 
        specified subject and resource pair. 

        As a reponse, an authorization decision will be returned.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessRequests'
              examples:
                example1:
                  summary: Authorization request to consume getTemp service operation in an specified service
                  value:
                      subject: "user123"
                      access-right: "consume"
                      resource: 
                        service: "eu.arrowhead.tempreadings-http-json@MWtzOXIpaUEsOyEhc1NsTwo"
                        service-operations: ["getTemp"]
                example2:
                  summary: Authorization request for writing on a service operation
                  value:  
                      subject: "MWtzOXIpaUEsOyEhc1NsTwo="
                      access-right: "write"
                      resource: 
                        service: "/OutsideTemp"
                        service-operations: ["write"]
                      
                  example3:
                    summary: Authorization request to check if a consumer has access to an event-type
                    value:  
                        subject: "user789"
                        access-right: "read"
                        resource: 
                          event-type: "motionDetected"
      responses:
        '200':
          description: Successful authorization
          content:
            application/json:
              schema:
                type: object
                properties:
                  authorizationDecisions:
                    type: array
                    items:
                      type: string
                      enum:
                        - allowed
                        - denied
              examples:
                example1:
                  value:
                    authorizationDecisions: ["allowed", "denied"]
                  summary: Example response with both allowed and denied decisions
                example2:
                  value: 
                    authorizationDecisions: ["allowed", "allowed", "denied"]
                  summary: Example response with multiple decisions
          headers:
            Cache-Control:
              $ref: '#/components/headers/Cache-Control'
            Limit:
              $ref: '#/components/headers/Limit'
        '400': { $ref: '#/components/responses/400-BadRequest' }
        '401': { $ref: '#/components/responses/401-Unauthorized' }
        '403': { $ref: '#/components/responses/403-Forbidden' }
        '406': { $ref: '#/components/responses/406-NotAcceptable' }
        '408': { $ref: '#/components/responses/408-RequestTimeout' }
        '411': { $ref: '#/components/responses/411-LengthRequired' }
        '413': { $ref: '#/components/responses/413-PayloadTooLarge' }
        '414': { $ref: '#/components/responses/414-URITooLarge' }
        '415': { $ref: '#/components/responses/415-UnsupportedMediaType' }
        '429': { $ref: '#/components/responses/429-TooManyRequests' }
        '431': { $ref: '#/components/responses/431-RequestHeaderFieldsTooLarge' }
        '500': { $ref: '#/components/responses/500-InternalServerError' }
        '503': { $ref: '#/components/responses/503-ServiceUnavailable' }

components:

  headers:

    Cache-Control:
      description: |
        If present, the value of this header may only include the `max-age`, `must-revalidate` and
        `no-store` response directives, all of which are defined in
        [RFC 9111 Section 5.2.2](https://datatracker.ietf.org/doc/html/rfc9111#name-response-directives).

        The `max-age` directive indicates for how many seconds the decision in the response may be
        cached before being requested again by the subject. The `must-revalidate` directive is used
        to forbid the subject from using the decision after the `max-age` has expired and the
        attempt to request it again failed. The `no-store` directive instructs the subject not to
        cache the decision at all.
      schema:
        type: string
      example: max-age=10, must-revalidate
      required: false

    Limit:
      description: |
        An indication of the maximum number of triplets the consuming system is allowed to include
        in its request.
      schema:
        type: number
        format: int32
        minimum: 0
      required: true

    Retry-After:
      description: |
        An indication, in seconds, of how long a subject is to wait before attempting the failed
        request again.
      schema:
        type: number
        format: int32
        minimum: 1
      required: true

  responses:

    400-BadRequest:
      description: |
        Invalid authorization basis submitted in request for an authorization decision.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }

    401-Unauthorized:
      description: |
        Consumer not yet authorized.

        The kind of authorization required _may_ be named in the error response.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }

    403-Forbidden:
      description: |
        Consumer is authorized, but lacks permission.

        If a particular parameter is the cause of this error, it will be named in the payload of the
        error response.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }

    406-NotAcceptable:
      description: |
        A request contains either of the `Accept`, `Accept-Encoding` or `Accept-Language` headers,
        and they do not allow for the service provider to respond using `application/json` as
        `Content-Type` or with an encoding or language that the service provider supports.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }

    408-RequestTimeout:
      description: |
        A request did not arrive in full within an arbitrary timeout decided by the provider of this
        service interface.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }

    411-LengthRequired:
      description: |
        The `Content-Length` header is missing in the request.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }

    413-PayloadTooLarge:
      description: |
        The payload in the request exceeds the size limit imposed by the service provider.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }

    414-URITooLarge:
      description: |
        The size of the request line in the request, which includes the HTTP version, method and
        URI, exceeds the limit imposed by the service provider.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }

    415-UnsupportedMediaType:
      description: |
        The request includes a payload encoded using a `Content-Type` unsupported by the service
        provider.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }

    429-TooManyRequests:
      description: |
        The consumer has sent too many request in a too short time span. The consumer is expected to
        wait the amount of time indicated in the `Retry-After` header before trying again.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }
      headers:
        Retry-After:
          $ref: '#/components/headers/Retry-After'

    431-RequestHeaderFieldsTooLarge:
      description: |
        The headers section in the request exceeds the limit imposed by the service provider. This
        response code may indicate that

        1. either the name or value of a field is too large,
        2. the combination of name and value in a field is too large, or
        3. the complete header section is too large.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }

    500-InternalServerError:
      description: |
        The server encountered an unexpected condition that prevented it from fulfilling the
        request.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }

    503-ServiceUnavailable:
      description: |
        The service provider is currently near its operating capacity or is undergoing maintenance.
        The consumer is expected to wait before trying again, as indicated by the `Retry-After`
        header in the response.
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }
      headers:
        Cache-Control:
          $ref: '#/components/headers/Retry-After'

  schemas:
    Group:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the personal group
        name:
          type: string
          description: Name of the personal group
        subjects:
          type: array
          items:
            $ref: '#/components/schemas/Subject'
      required:
        - id
        - name
        - subjects

    NewGroupRequest:
      type: object
      properties:
        name:
          type: string
          description: Name of the new group
        users:
          type: array
          description: Initial list of users to add to the group
          items:
            $ref: '#/components/schemas/Subject'
      required:
        - name

    AccessRequests:
      description: |
        Three objects identifying a _consumer_, an _operation_ and an _resource_, in that order.
        Together they describe how a certain consumer wishes do perform a certain operation on a
        certain resource.
      type: object
      properties:
        consumer:
          type: string
          description: The identifier of the consumer system making the request. The format of the string is 
            dependant on the Authentication mechanism used. (e.g., a certificate string, token, id, etc)
        access-right:
          type: string
          description: String identifier for the access right needed to be authorized. These access rights
            must be pre-defined within the policy engine used. ("consume", "read", "write", "delete", "update", etc)
        resource:
          $ref: '#/components/schemas/Resource'
      required:
        - consumer
        - access-right
        - resource

    Error:
      description: |
        An indication of why a received request was rejected. It is formulated with the assumption
        that the subject knows of and can interpret the status code in the response.
      type: object
      properties:
        message:
          description: A human-readable explanation of why the request was rejected.
          type: string

    Resource:
      description: |
        Identifier of the resource over which the authorization policy is to be defined. 
        `Service` represents the unique identifier of the desired service. `Service-operations`refers to the 
        specific operation within the specified service. This can be a list of service operations. Leaving this 
        field blank should only grant permission to the Service's ping operation. Finally, the `Event type`shold
        be used when refering to events.
      type: object
      properties:
        service: 
          type: string
        service-operations: 
          type: array
          items:
            type: string
        event-type:
          type: string
    
    Policy:
      description: |
        An object containing the relevant information for the creation of an authorization rule. 
        The authorization rule contains 3 main parameters: _consumer_, _operation_ and _resource_, where the resource 
        refers to the service and service operations that are relevant to the authorization rule. Moreover, this 
        permission can be either a grant operation or a prohibition. In other words, a grant authorization rule can 
        add the consumer to the whitelist of consumers that have access to the specified resource. On the other hand,
        a prohibition authorization rule adds that same consumer to the blacklist for the specified resource. 
      type: object
      properties:
        resource: 
          $ref: '#/components/schemas/Resource'
        operation: 
          type: array
          items: 
            type: string
        subject-id: 
          type: string
        permission-type:
          type: string
          enum:
            - grant
            - prohibit

    Subject:
      description: |
        This object contains information about the consumer system, or a personal group. When refering to 
        a `Subject` of subject-type _consumer_, a unique identifier for the consumer system should be provided.
        When refering to a subject-type _group_, the identifier of a previously defined personal group should 
        be provided. 
      type: object
      properties:
        subject-type: 
          type: string
          enum:
            - consumer
            - group
        subject-id:
          type: string
      required:
        - subject-type
        - subject-id
    
    
   